added a check for the data/ folder in github actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,6 +30,14 @@ jobs:
       - name: 🛠️ Run data update script
         run: Rscript ptagis_processing.R
         
+      - name: Check for data/ contents
+        run: |
+        echo = "=== Does data/ exist? ==="
+        if [ -d "data" ]; then echo "Yes, data/ exists."; else echo "No, data/ does NOT exist."; fi
+        echo ""
+        echo " === Listing contents of data/ ==="
+        ls -la data || echo "data/ folder is missing or empty"
+
       - name: 🚀 Deploy to shinyapps.io
         env:
           SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
